### ISSUE TITLE
Transmitting Value between 0 and 1023

### ISSUE THREAD

**Issue by jayonexx** [chandrawi/LoRaRF-Arduino#11]
Im trying to transmit my analog input from Arduino to a Raspberry pi using your example code on both devices.
However im receiving only a value of 255 at the Rapi. Is there a way to get it working with the full 10 bit ADC value ?
Thanks in advance

**Comment by chandrawi** [comment]
Yes, there is a way. You must split your 10-bit ADC value into 2 bytes. On arduino (transmitter), the code would be like this

```cpp
  int val = analogRead(0);
  unit8_t valBytes[2] = {val >> 8, val};
  LoRa.beginPacket();
  LoRa.write(valBytes, 2);
  LoRa.endPacket();
```
