### ISSUE TITLE
E220-400MM22S 

### ISSUE THREAD

**Issue by AdamHawkTrack** [chandrawi/LoRaRF-Arduino#18]
Good morning, I've spent hours and hours trying to get the new E220-400MM22S module working. Have you managed to get the code to work on this module at all? Many thanks, Adam

**Comment by chandrawi** [comment]
I never tried to use LLCC68 module like E220-400MM22S. But someone told me that they able to use this library with LLCC68. Did you try [SX126x_LoRa_receiver](https://github.com/chandrawi/LoRaRF-Arduino/blob/main/examples/SX126x/SX126x_LoRa_receiver/SX126x_LoRa_receiver.ino) and [SX126x_LoRa_transmitter](https://github.com/chandrawi/LoRaRF-Arduino/blob/main/examples/SX126x/SX126x_LoRa_transmitter/SX126x_LoRa_transmitter.ino) examples?

What is error message you got? Can you show me the serial monitor output when trying those examples?

**Comment by AdamHawkTrack** [comment]
Unfortunately I haven't managed to communicate with the module at all. I was a little confused at the wiring and have tried multiple combinations but without success. The ebyte user manual shows an example diagram and shows mosi to miso and miso to mosi, but neither will work ..
![Screenshot_20230703_134121](https://github.com/chandrawi/LoRaRF-Arduino/assets/138394558/6446390a-825e-4b31-a5f1-4cfa9af6461d)

**Comment by chandrawi** [comment]
The correct wiring for SPI is MISO <-> MISO and MOSI <-> MOSI. I believe that user manual is wrong.
What kind Arduino board you used?
Ebyte module configure the DIO3 as TXCO control. You must make sure that your sketch has following code in setup
```cpp
  uint8_t dio3Voltage = SX126X_DIO3_OUTPUT_1_8;
  uint32_t tcxoDelay = SX126X_TCXO_DELAY_10;
  LoRa.setDio3TcxoCtrl(dio3Voltage, tcxoDelay);
```
What the output of serial monitor? If there is no output, you should push the reset button. When no connection occured or wrong wiring, the `SX126x_LoRa_receiver` and `SX126x_LoRa_transmitter examples` print error message.

**Comment by AdamHawkTrack** [comment]
I have been using a Arduino Pro Mini, the same board as I've been using for a SX1278 lora module that works fine. I'm powering them both independently with 3.3v supply. I have an Uno that I could use, but I was cautious about 5v on the pins as apparently the chip is sensitive to higher voltages. I will remake the circuit and check the serial monitor. 

Could you please advise if the rx and tx need connecting? The instructions say if module has it then should be connected, but table says unused? Thanks

**Comment by krishank652** [comment]
Dear @AdamHawkTrack ,
I have Same module E200-400M22S and E200-400MM22S.

Have you success to build communication between MCU and Ebyte Module.

Please help me I need your help.

**Comment by AdamHawkTrack** [comment]
> Dear @AdamHawkTrack , I have Same module E200-400M22S and E200-400MM22S.
> 
> Have you success to build communication between MCU and Ebyte Module.
> 
> Please help me I need your help.

Dear @krishank652,

I have been really busy but coincidentally I got back on my project at the weekend and managed to get communication from the modules.

I used the example codes for the SX126#. I commented out tcxo and uncommented xtal. I changed the frequency to 434mhz, and commented out the sync word for testing. That worked.

I did not need to connect rx, tx, dio pins. Just miso, most, sck, nss, reset, and busy pin.

I hope this helps 🤞😁

**Comment by krishank652** [comment]
Thank you, @AdamHawkTrack, for your assistance. How did you connect MISO and MOSI? My understanding was that the connection should be as follows:
MOSI <> MOSI
MISO <> MISO

However, the diagram you provided suggests a different configuration:
MOSI <> MISO
MISO <> MOSI

If you don't mind sharing your contact information please?  Please understand It will help me.

If possible, please share you contact details: [Here.](https://forms.gle/Z4ichzBQQRTfXoMx8) 
Your information will be sent directly to me. Thank you in advance.

**Comment by AdamHawkTrack** [comment]
@krishank652 I would prefer to discuss here then it may help others if that's ok

Mine works as per...

MOSI <> MOSI
MISO <> MISO

You need to understand I am very amateur at this myself so trying to learn. Have had good success with lora sx1278, but am new to eByte

**Comment by AdamHawkTrack** [comment]
Thanks @chandrawi I got communication with your code 🙂
