### ISSUE TITLE
LLCC68 Initialization time

### ISSUE THREAD

**Issue by ramonverde** [chandrawi/LoRaRF-Arduino#9]
I have checked that, with some fast CPU devices and the Ra-01SC module (LLCC68), the "begin" method can return an error because the LLCC68 cannot initialialize between the sx126x_reset and the send of sx126x_setStandby.
Checking the LLCC68 datasheet, in the table "Table 8-1: SPI Timing Requirements", there is a "t10" time of 100us that must be waited when switching from SLEEP to STDBY_RC mode, and in "8.2.2 SPI Timing When the Transceiver Leaves Sleep Mode" it's said "	"...This is also true for start-up at battery insertion or after a hard reset."

I have tested adding that small delay after the reset and it makes the LLCC68 to init OK all the times.
I hace created a pull request: #8

**Comment by chandrawi** [comment]
I have check LLCC68 datasheet and just notice that 100 µs delay is needed after switch NSS to HIGH for waking SX1261, SX1262, and LLCC68. Good job for noticing it.
I just merge your pull request.
I will publish new release for this fix.
